import type { EducationItem } from "./types";

export const formationData: EducationItem[] = [
  {
    type: "education",
    title: "Bootcamp Full Stack (540h)",
    institution: "Generation Chile",
    year: "2025",
    date: "2025-01-15",
    description:
      "Programa intensivo de desarrollo full-stack con enfoque en tecnologías modernas y metodologías ágiles.",
    details: [
      "Frontend con React.js",
      "Backend con Node.js, Express y Spring Boot",
      "Bases de datos SQL / NoSQL",
      "Testing y CI/CD",
      "Despliegue en cloud (Vercel, GCP, AWS)",
    ],
    duration: "540 horas",
    location: "Santiago, Chile",
    skills: ["React", "Node.js", "Spring Boot"],
    status: "Completado",
  },
  {
    type: "certification",
    title: "React: De cero a experto",
    institution: "Udemy",
    year: "2024",
    date: "2024-11-20",
    description: "Curso completo de React.js desde fundamentos hasta temas avanzados.",
    duration: "40 horas",
    certificateUrl: "#",
    skills: ["React", "Redux", "Testing"],
    status: "Completado",
  },
  {
    type: "certification",
    title: "Docker: Guía práctica para desarrolladores",
    institution: "Udemy",
    year: "2024",
    date: "2024-10-15",
    description: "Containerización y buenas prácticas para entornos productivos.",
    duration: "25 horas",
    certificateUrl: "#",
    skills: ["Docker", "DevOps"],
    status: "Completado",
  },
  {
    type: "education",
    title: "Ingeniería en Informática",
    institution: "Duoc UC",
    year: "2021",
    date: "2021-12-15",
    description: "Título profesional en Ingeniería en Informática con énfasis en desarrollo de software.",
    duration: "4 años",
    location: "Santiago, Chile",
    skills: ["Java", "SQL", "Patrones de diseño"],
    status: "Completado",
  },
]; 