import type { Skill, ExperienceDetail, Project, EducationItem } from "./types"

export const skillsData: Skill[] = [
  {
    name: "JavaScript",
    rating: 9,
    category: "Lenguajes",
    concepts: [
      { name: "ES6+ Features", learned: true },
      { name: "Async/Await", learned: true },
      { name: "Closures", learned: true },
      { name: "Prototypes", learned: true },
      { name: "Event Loop", learned: true },
      { name: "Modules", learned: true },
      { name: "Destructuring", learned: true },
      { name: "Arrow Functions", learned: true },
    ],
  },
  {
    name: "TypeScript",
    rating: 8,
    category: "Lenguajes",
    concepts: [
      { name: "Type Annotations", learned: true },
      { name: "Interfaces", learned: true },
      { name: "Generics", learned: true },
      { name: "Union Types", learned: true },
      { name: "Decorators", learned: false },
      { name: "Advanced Types", learned: true },
      { name: "Type Guards", learned: true },
    ],
  },
  {
    name: "React.js",
    rating: 9,
    category: "Frontend",
    concepts: [
      { name: "Hooks", learned: true },
      { name: "Context API", learned: true },
      { name: "Component Lifecycle", learned: true },
      { name: "State Management", learned: true },
      { name: "JSX", learned: true },
      { name: "Props & State", learned: true },
      { name: "Custom Hooks", learned: true },
      { name: "Performance Optimization", learned: true },
    ],
  },
  {
    name: "Next.js",
    rating: 8,
    category: "Frontend",
    concepts: [
      { name: "App Router", learned: true },
      { name: "Server Components", learned: true },
      { name: "API Routes", learned: true },
      { name: "Static Generation", learned: true },
      { name: "Server-Side Rendering", learned: true },
      { name: "Middleware", learned: false },
      { name: "Image Optimization", learned: true },
    ],
  },
  {
    name: "Node.js",
    rating: 8,
    category: "Backend",
    concepts: [
      { name: "Express.js", learned: true },
      { name: "Middleware", learned: true },
      { name: "File System", learned: true },
      { name: "Streams", learned: false },
      { name: "Event Emitters", learned: true },
      { name: "NPM/Yarn", learned: true },
      { name: "Authentication", learned: true },
    ],
  },
  {
    name: "Spring Boot",
    rating: 7,
    category: "Backend",
    concepts: [
      { name: "REST APIs", learned: true },
      { name: "JPA/Hibernate", learned: true },
      { name: "Security", learned: true },
      { name: "Dependency Injection", learned: true },
      { name: "Microservices", learned: false },
      { name: "Testing", learned: true },
      { name: "Configuration", learned: true },
    ],
  },
  {
    name: "MySQL",
    rating: 8,
    category: "Bases de Datos",
    concepts: [
      { name: "SQL Queries", learned: true },
      { name: "Joins", learned: true },
      { name: "Indexing", learned: true },
      { name: "Stored Procedures", learned: false },
      { name: "Transactions", learned: true },
      { name: "Database Design", learned: true },
      { name: "Performance Optimization", learned: true },
    ],
  },
  {
    name: "MongoDB",
    rating: 7,
    category: "Bases de Datos",
    concepts: [
      { name: "Document Structure", learned: true },
      { name: "Aggregation Pipeline", learned: true },
      { name: "Indexing", learned: true },
      { name: "Mongoose ODM", learned: true },
      { name: "Replica Sets", learned: false },
      { name: "Sharding", learned: false },
      { name: "GridFS", learned: false },
    ],
  },
  {
    name: "Docker",
    rating: 7,
    category: "DevOps",
    concepts: [
      { name: "Containerization", learned: true },
      { name: "Dockerfile", learned: true },
      { name: "Docker Compose", learned: true },
      { name: "Image Management", learned: true },
      { name: "Networking", learned: false },
      { name: "Volumes", learned: true },
      { name: "Multi-stage Builds", learned: false },
    ],
  },
  {
    name: "AWS",
    rating: 6,
    category: "DevOps",
    concepts: [
      { name: "EC2", learned: true },
      { name: "S3", learned: true },
      { name: "RDS", learned: true },
      { name: "Lambda", learned: false },
      { name: "CloudWatch", learned: true },
      { name: "IAM", learned: true },
      { name: "API Gateway", learned: false },
    ],
  },
]

export const experienceData: ExperienceDetail[] = [
  {
    title: "Desarrollador Freelance (WooCommerce)",
    period: "2025",
    location: "Santiago, Chile (Remoto)",
    description:
      "Desarrollo de soluciones e-commerce personalizadas para microemprendedoras, enfocándome en crear tiendas online funcionales y atractivas que impulsen sus negocios.",
    responsibilities: [
      "Implementación completa de tiendas WooCommerce desde cero",
      "Personalización de temas y funcionalidades específicas",
      "Integración de pasarelas de pago locales e internacionales",
      "Optimización SEO y performance de las tiendas",
      "Capacitación a clientes en el uso de la plataforma",
      "Mantenimiento y soporte técnico continuo",
    ],
    achievements: [
      "Incremento promedio del 150% en ventas online de los clientes",
      "Reducción del 40% en tiempo de carga de las tiendas",
      "100% de satisfacción del cliente en proyectos entregados",
      "Implementación de sistema de inventario automatizado",
    ],
    technologies: ["WordPress", "WooCommerce", "PHP", "MySQL", "JavaScript", "CSS", "HTML"],
    teamSize: "Individual",
    projectType: "E-commerce",
  },
  {
    title: "Customer Specialist IT",
    company: "ETPAY SpA",
    period: "Jun 2021 - Dic 2021",
    location: "Santiago, Chile",
    description:
      "Especialista en soporte técnico y resolución de incidencias para plataforma de pagos digitales, actuando como puente entre clientes y el equipo de desarrollo.",
    responsibilities: [
      "Monitoreo proactivo de sistemas usando AWS CloudWatch",
      "Resolución de incidencias técnicas de nivel 2 y 3",
      "Soporte a integraciones de APIs REST para clientes enterprise",
      "Documentación técnica de procesos y soluciones",
      "Coordinación directa con equipos de desarrollo para escalamiento",
      "Análisis de logs y diagnóstico de problemas de performance",
    ],
    achievements: [
      "Reducción del 60% en tiempo de resolución de incidencias",
      "Implementación de alertas proactivas que redujeron downtime en 30%",
      "Creación de base de conocimiento que mejoró eficiencia del equipo",
      "Satisfacción del cliente superior al 95% en encuestas de soporte",
    ],
    technologies: ["AWS CloudWatch", "REST APIs", "SQL", "Python", "Postman", "Jira", "Confluence"],
    teamSize: "Equipo de 8 personas",
    projectType: "Fintech/Pagos",
  },
  {
    title: "Desarrollador Shopify (Práctica)",
    company: "Ducklife Media",
    period: "Oct 2020 - Dic 2020",
    location: "Santiago, Chile",
    description:
      "Práctica profesional enfocada en el desarrollo y personalización de tiendas Shopify, trabajando en mejoras de UX/UI y optimización de conversiones.",
    responsibilities: [
      "Modificación y personalización de temas Shopify existentes",
      "Desarrollo de componentes personalizados con Liquid",
      "Implementación de diseños responsive y mobile-first",
      "Optimización de velocidad de carga y SEO técnico",
      "Testing cross-browser y debugging de funcionalidades",
      "Colaboración con diseñadores para implementar mockups",
    ],
    achievements: [
      "Mejora del 25% en tasa de conversión de tiendas optimizadas",
      "Implementación exitosa de 15+ tiendas Shopify",
      "Reducción del 35% en tasa de rebote mediante mejoras UX",
      "Certificación en Shopify Partner Program",
    ],
    technologies: ["Shopify", "Liquid", "HTML", "CSS", "JavaScript", "Sass", "Git"],
    teamSize: "Equipo de 5 personas",
    projectType: "E-commerce",
  },
]

export const projectsData: Project[] = [
  {
    name: "Ecomarket",
    description: "E-commerce full stack con React y Spring Boot. MySQL, despliegue en Vercel/GCP.",
    longDescription:
      "Plataforma de e-commerce completa enfocada en productos ecológicos y sostenibles. Incluye sistema de gestión de inventario, carrito de compras, procesamiento de pagos, panel de administración y sistema de reseñas. Implementa autenticación JWT, optimización de imágenes y SEO.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["React", "Spring Boot", "MySQL", "JWT", "Vercel", "GCP"],
    frameworks: ["React", "Spring Boot"],
    languages: ["JavaScript", "Java", "SQL"],
    role: ["Frontend", "Backend", "Full Stack"],
    links: [
      { label: "Frontend", url: "#" },
      { label: "Backend", url: "#" },
      { label: "Demo", url: "#" },
    ],
    status: "Completado",
    year: "2024",
  },
  {
    name: "BancoSimple",
    description: "App bancaria con autenticación JWT. React + Spring Boot + MySQL.",
    longDescription:
      "Aplicación bancaria simulada con funcionalidades completas de gestión financiera. Incluye transferencias, historial de transacciones, gestión de cuentas, reportes financieros y dashboard administrativo. Implementa seguridad robusta con JWT y encriptación de datos sensibles.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["React", "Spring Boot", "MySQL", "JWT", "Spring Security"],
    frameworks: ["React", "Spring Boot"],
    languages: ["JavaScript", "Java", "SQL"],
    role: ["Frontend", "Backend", "Full Stack"],
    links: [
      { label: "Frontend", url: "#" },
      { label: "Backend", url: "#" },
      { label: "Demo", url: "#" },
    ],
    status: "Completado",
    year: "2024",
  },
  {
    name: "Gestor de Tareas CLI",
    description: "App Node.js interactiva (Inquirer).",
    longDescription:
      "Herramienta de línea de comandos para gestión de tareas y productividad. Permite crear, editar, eliminar y organizar tareas con categorías, prioridades y fechas límite. Incluye reportes de productividad, exportación de datos y sincronización con calendarios externos.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["Node.js", "Inquirer", "Commander", "Chalk", "JSON"],
    frameworks: ["Node.js"],
    languages: ["JavaScript"],
    role: ["Backend", "CLI"],
    links: [
      { label: "Demo", url: "#" },
      { label: "GitHub", url: "#" },
      { label: "NPM", url: "#" },
    ],
    status: "Completado",
    year: "2024",
  },
  {
    name: "Portafolio Web",
    description: "Sitio MERN personal con despliegue en Vercel.",
    longDescription:
      "Portafolio personal desarrollado con stack MERN, featuring diseño responsive, modo oscuro, animaciones suaves y optimización SEO. Incluye blog técnico, galería de proyectos, formulario de contacto y panel de administración para gestión de contenido.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["MongoDB", "Express", "React", "Node.js", "Vercel"],
    frameworks: ["React", "Express"],
    languages: ["JavaScript", "HTML", "CSS"],
    role: ["Frontend", "Backend", "Full Stack"],
    links: [
      { label: "Enlace", url: "#" },
      { label: "GitHub", url: "#" },
    ],
    status: "En desarrollo",
    year: "2024",
  },
  {
    name: "API RestaurantManager",
    description: "API REST para gestión de restaurantes con Spring Boot.",
    longDescription:
      "API completa para gestión de restaurantes que incluye manejo de menús, pedidos, inventario, empleados y reportes financieros. Implementa patrones de diseño, documentación con Swagger, testing unitario y integración continua.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["Spring Boot", "PostgreSQL", "Swagger", "JUnit", "Docker"],
    frameworks: ["Spring Boot"],
    languages: ["Java", "SQL"],
    role: ["Backend", "API"],
    links: [
      { label: "GitHub", url: "#" },
      { label: "Swagger Docs", url: "#" },
    ],
    status: "Completado",
    year: "2023",
  },
  {
    name: "Dashboard Analytics",
    description: "Dashboard de analytics con Next.js y Chart.js.",
    longDescription:
      "Dashboard interactivo para visualización de datos y analytics empresariales. Incluye gráficos dinámicos, filtros avanzados, exportación de reportes, notificaciones en tiempo real y integración con múltiples fuentes de datos.",
    image: "/placeholder.svg?height=200&width=400",
    tech: ["Next.js", "Chart.js", "Tailwind", "Prisma", "PostgreSQL"],
    frameworks: ["Next.js"],
    languages: ["TypeScript", "SQL"],
    role: ["Frontend", "Full Stack"],
    links: [
      { label: "Demo", url: "#" },
      { label: "GitHub", url: "#" },
    ],
    status: "En desarrollo",
    year: "2024",
  },
]

export const formationData: EducationItem[] = [
  {
    type: "education",
    title: "Bootcamp Full Stack (540h)",
    institution: "Generation Chile",
    year: "2025",
    date: "2025-01-15",
    description:
      "Programa intensivo de desarrollo full-stack con enfoque en tecnologías modernas y metodologías ágiles.",
    details: [
      "Frontend con React.js",
      "Backend con Node.js, Express y Spring Boot",
      "Bases de datos SQL / NoSQL",
      "Testing y CI/CD",
      "Despliegue en cloud (Vercel, GCP, AWS)",
    ],
    duration: "540 horas",
    location: "Santiago, Chile",
    skills: ["React", "Node.js", "Spring Boot"],
    status: "Completado",
  },
  {
    type: "certification",
    title: "React: De cero a experto",
    institution: "Udemy",
    year: "2024",
    date: "2024-11-20",
    description: "Curso completo de React.js desde fundamentos hasta temas avanzados.",
    duration: "40 horas",
    certificateUrl: "#",
    skills: ["React", "Redux", "Testing"],
    status: "Completado",
  },
  {
    type: "certification",
    title: "Docker: Guía práctica para desarrolladores",
    institution: "Udemy",
    year: "2024",
    date: "2024-10-15",
    description: "Containerización y buenas prácticas para entornos productivos.",
    duration: "25 horas",
    certificateUrl: "#",
    skills: ["Docker", "DevOps"],
    status: "Completado",
  },
  {
    type: "education",
    title: "Ingeniería en Informática",
    institution: "Duoc UC",
    year: "2021",
    date: "2021-12-15",
    description: "Título profesional en Ingeniería en Informática con énfasis en desarrollo de software.",
    duration: "4 años",
    location: "Santiago, Chile",
    skills: ["Java", "SQL", "Patrones de diseño"],
    status: "Completado",
  },
]
