import type { Skill } from "./types";

export const skillsData: Skill[] = [
  {
    name: "JavaScript",
    rating: 9,
    category: "Lenguajes",
    concepts: [
      { name: "ES6+ Features", learned: true },
      { name: "Async/Await", learned: true },
      { name: "Closures", learned: true },
      { name: "Prototypes", learned: true },
      { name: "Event Loop", learned: true },
      { name: "Modules", learned: true },
      { name: "Destructuring", learned: true },
      { name: "Arrow Functions", learned: true },
    ],
  },
  {
    name: "TypeScript",
    rating: 8,
    category: "Lenguajes",
    concepts: [
      { name: "Type Annotations", learned: true },
      { name: "Interfaces", learned: true },
      { name: "Generics", learned: true },
      { name: "Union Types", learned: true },
      { name: "Decorators", learned: false },
      { name: "Advanced Types", learned: true },
      { name: "Type Guards", learned: true },
    ],
  },
  {
    name: "React.js",
    rating: 9,
    category: "Frontend",
    concepts: [
      { name: "Hooks", learned: true },
      { name: "Context API", learned: true },
      { name: "Component Lifecycle", learned: true },
      { name: "State Management", learned: true },
      { name: "JSX", learned: true },
      { name: "Props & State", learned: true },
      { name: "Custom Hooks", learned: true },
      { name: "Performance Optimization", learned: true },
    ],
  },
  {
    name: "Next.js",
    rating: 8,
    category: "Frontend",
    concepts: [
      { name: "App Router", learned: true },
      { name: "Server Components", learned: true },
      { name: "API Routes", learned: true },
      { name: "Static Generation", learned: true },
      { name: "Server-Side Rendering", learned: true },
      { name: "Middleware", learned: false },
      { name: "Image Optimization", learned: true },
    ],
  },
  {
    name: "Node.js",
    rating: 8,
    category: "Backend",
    concepts: [
      { name: "Express.js", learned: true },
      { name: "Middleware", learned: true },
      { name: "File System", learned: true },
      { name: "Streams", learned: false },
      { name: "Event Emitters", learned: true },
      { name: "NPM/Yarn", learned: true },
      { name: "Authentication", learned: true },
    ],
  },
  {
    name: "Spring Boot",
    rating: 7,
    category: "Backend",
    concepts: [
      { name: "REST APIs", learned: true },
      { name: "JPA/Hibernate", learned: true },
      { name: "Security", learned: true },
      { name: "Dependency Injection", learned: true },
      { name: "Microservices", learned: false },
      { name: "Testing", learned: true },
      { name: "Configuration", learned: true },
    ],
  },
  {
    name: "MySQL",
    rating: 8,
    category: "Bases de Datos",
    concepts: [
      { name: "SQL Queries", learned: true },
      { name: "Joins", learned: true },
      { name: "Indexing", learned: true },
      { name: "Stored Procedures", learned: false },
      { name: "Transactions", learned: true },
      { name: "Database Design", learned: true },
      { name: "Performance Optimization", learned: true },
    ],
  },
  {
    name: "MongoDB",
    rating: 7,
    category: "Bases de Datos",
    concepts: [
      { name: "Document Structure", learned: true },
      { name: "Aggregation Pipeline", learned: true },
      { name: "Indexing", learned: true },
      { name: "Mongoose ODM", learned: true },
      { name: "Replica Sets", learned: false },
      { name: "Sharding", learned: false },
      { name: "GridFS", learned: false },
    ],
  },
  {
    name: "Docker",
    rating: 7,
    category: "DevOps",
    concepts: [
      { name: "Containerization", learned: true },
      { name: "Dockerfile", learned: true },
      { name: "Docker Compose", learned: true },
      { name: "Image Management", learned: true },
      { name: "Networking", learned: false },
      { name: "Volumes", learned: true },
      { name: "Multi-stage Builds", learned: false },
    ],
  },
  {
    name: "AWS",
    rating: 6,
    category: "DevOps",
    concepts: [
      { name: "EC2", learned: true },
      { name: "S3", learned: true },
      { name: "RDS", learned: true },
      { name: "Lambda", learned: false },
      { name: "CloudWatch", learned: true },
      { name: "IAM", learned: true },
      { name: "API Gateway", learned: false },
    ],
  },
];

export const habilidadesTecnicasHome = [
  {
    categoria: "Lenguajes",
    skills: ["JavaScript", "TypeScript", "Java", "SQL", "Python"],
  },
  {
    categoria: "Frontend",
    skills: ["React.js", "Next.js", "HTML", "CSS", "Tailwind"],
  },
  {
    categoria: "Backend",
    skills: ["Node.js", "Express", "Spring Boot"],
  },
  {
    categoria: "Bases de Datos",
    skills: ["MySQL", "MongoDB", "PostgreSQL"],
  },
  {
    categoria: "DevOps",
    skills: ["Git", "Docker", "Vercel", "GCP", "AWS"],
  },
  {
    categoria: "Otros",
    skills: ["JWT", "REST APIs", "MVC", "Testing Unitario", "CI/CD", "Scrum"],
  },
]; 